### ISSUE TITLE
Fail `pec init` on v0.8.1

### ISSUE THREAD

**Issue by hfm** [yaocloud/pec#40]
```console
$ bundle exec pec init
/private/tmp/dokku/.bundle/ruby/2.2.0/gems/pec-0.8.1/lib/pec/command/init.rb:3:in `run': wrong number of arguments (1 for 0) (ArgumentError)
        from /private/tmp/dokku/.bundle/ruby/2.2.0/gems/pec-0.8.1/lib/pec/cli.rb:50:in `_sub_command'
        from /private/tmp/dokku/.bundle/ruby/2.2.0/gems/pec-0.8.1/lib/pec/cli.rb:7:in `init'
        from /private/tmp/dokku/.bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /private/tmp/dokku/.bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /private/tmp/dokku/.bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /private/tmp/dokku/.bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /private/tmp/dokku/.bundle/ruby/2.2.0/gems/pec-0.8.1/bin/pec:3:in `<top (required)>'
        from /private/tmp/dokku/.bundle/ruby/2.2.0/bin/pec:23:in `load'
        from /private/tmp/dokku/.bundle/ruby/2.2.0/bin/pec:23:in `<main>'
```

**Comment by hfm** [comment]
`lib/pec/command/init.rb` has no option.

```rb
module Pec::Command
  class Init < Base
    def self.run
      Pec::Init.show_env_setting
      Pec::Init.create_template_dir
      Pec::Init.create_sample_config
    end
  end
end
```

But `_sub_command` of cli.rb calls `run(filter_hosts)` :cry:  :

```rb
    no_commands do
      def _sub_command(filter_hosts, options)
        Pec.options options
        Object.const_get("Pec::Command::#{caller[0][/`([^']*)'/, 1].capitalize}").run(filter_hosts)  # Pec::Command::Init.run(filter_hosts) => Error!
      end
    end
```

**Comment by pyama86** [comment]
Oh...
I will tell you what.

```
module Pec::Command
  class Init < Base
    def self.run(_null)
      Pec::Init.show_env_setting
      Pec::Init.create_template_dir
      Pec::Init.create_sample_config
    end
  end
end
```
